pipeline {

    agent any 

    stages {
        stage('Checkout Codebase'){
            steps{
                checkout scm: [$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[credentialsId: 'github-ssh-key', url: 'git@github.com:mnorm88/slack-bot-jenkins-integration.git']]] 
            }
        }

        stage('Build') {
            steps {
                echo 'Building Codebase'
            }
        }

        stage('Test'){
            steps {
                echo 'Running Tests on changes'
            }
        }
        
        stage('Deploy'){
            steps{
                echo 'Done!'
            }
        }
    }

    post {

        always {
            echo 'Sending Slack message'
            sh "curl --header 'Content-Type: application/json' --request POST --data '{\"buildurl\": \"xyz\",\"buildresult\":\"xyz\", \"buildnumber\": 120, \"jobname\":\"testjob\"}' http://172.17.0.1:8091/sendSlackMessage"
        }
    }
}